# Copyright 2026 TAK-Solutions LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""enrollment tokens and device certificates

Revision ID: 29d37a3a091c
Revises: 57f4870d7e11
Create Date: 2026-08-30 22:36:46.997851

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '29d37a3a091c'
down_revision: str | None = '57f4870d7e11'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrollment_token',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('prefix', sa.String(length=12), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('use_count', sa.Integer(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('enrollment_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_enrollment_token_token_hash'), ['token_hash'], unique=True)

    op.create_table('device_certificate',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('serial_hex', sa.String(length=64), nullable=False),
    sa.Column('not_valid_after', sa.DateTime(timezone=True), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device_certificate', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_certificate_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_certificate_serial_hex'), ['serial_hex'], unique=True)

    op.create_table('enrollment_token_group',
    sa.Column('token_id', sa.Uuid(), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['device_group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['token_id'], ['enrollment_token.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_id', 'group_id')
    )
    op.create_table('enrollment_token_tag',
    sa.Column('token_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['token_id'], ['enrollment_token.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enrollment_token_tag')
    op.drop_table('enrollment_token_group')
    with op.batch_alter_table('device_certificate', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_certificate_serial_hex'))
        batch_op.drop_index(batch_op.f('ix_device_certificate_device_id'))

    op.drop_table('device_certificate')
    with op.batch_alter_table('enrollment_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_enrollment_token_token_hash'))

    op.drop_table('enrollment_token')
    # ### end Alembic commands ###
