# Copyright 2026 TAK-Solutions LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""managed files and selections

Revision ID: 2a84424ae9f5
Revises: 746dc87d9b3d
Create Date: 2026-08-31 12:55:20.070118

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text  # autogenerate emits a bare Text() inside JSONB variants

import app.db.base  # autogenerate emits app.db.base.UtcDateTime for timestamps


revision: str = '2a84424ae9f5'
down_revision: str | None = '746dc87d9b3d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('managed_file',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('media_type', sa.String(length=128), nullable=False),
    sa.Column('is_archive', sa.Boolean(), nullable=False),
    sa.Column('artifact_sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', app.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artifact_sha256'], ['artifact.sha256'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('managed_file', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_managed_file_artifact_sha256'), ['artifact_sha256'], unique=False)

    op.create_table('device_file_selection',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('file_id', sa.Uuid(), nullable=False),
    sa.Column('applied_at', app.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['managed_file.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'file_id', name='uq_device_file_selection')
    )
    with op.batch_alter_table('device_file_selection', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_file_selection_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_file_selection_file_id'), ['file_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_file_selection', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_file_selection_file_id'))
        batch_op.drop_index(batch_op.f('ix_device_file_selection_device_id'))

    op.drop_table('device_file_selection')
    with op.batch_alter_table('managed_file', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_managed_file_artifact_sha256'))

    op.drop_table('managed_file')
    # ### end Alembic commands ###
