"""initial schema

Revision ID: 57f4870d7e11
Revises: 
Create Date: 2026-08-30 22:08:04.694047

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '57f4870d7e11'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('serial_number', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('imei', sa.String(length=32), nullable=True),
    sa.Column('os_version', sa.String(length=32), nullable=True),
    sa.Column('agent_version', sa.String(length=32), nullable=True),
    sa.Column('enrollment_state', sa.Enum('PENDING', 'ENROLLED', 'RETIRED', name='enrollmentstate', native_enum=False, length=16), nullable=False),
    sa.Column('state_version', sa.Integer(), nullable=False),
    sa.Column('last_checkin_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_serial_number'), ['serial_number'], unique=True)

    op.create_table('device_group',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('policy',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('policy_type', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('policy', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_policy_policy_type'), ['policy_type'], unique=False)

    op.create_table('tag',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('device_group_member',
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['device_group.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('device_id', 'group_id')
    )
    op.create_table('device_tag_member',
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('device_id', 'tag_id')
    )
    op.create_table('effective_policy_cache',
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('state_version', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('stale', sa.Boolean(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('device_id')
    )
    op.create_table('policy_version',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('policy_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('spec', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['policy.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('policy_id', 'version', name='uq_policy_version')
    )
    with op.batch_alter_table('policy_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_policy_version_policy_id'), ['policy_id'], unique=False)

    op.create_table('assignment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('policy_id', sa.Uuid(), nullable=False),
    sa.Column('pinned_version_id', sa.Uuid(), nullable=True),
    sa.Column('scope', sa.Enum('DEVICE', 'GROUP', 'TAG', name='assignmentscope', native_enum=False, length=16), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=True),
    sa.Column('group_id', sa.Uuid(), nullable=True),
    sa.Column('tag_id', sa.Uuid(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('(CASE WHEN device_id IS NOT NULL THEN 1 ELSE 0 END) + (CASE WHEN group_id IS NOT NULL THEN 1 ELSE 0 END) + (CASE WHEN tag_id IS NOT NULL THEN 1 ELSE 0 END) = 1', name='ck_assignment_single_target'),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['device_group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pinned_version_id'], ['policy_version.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['policy_id'], ['policy.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assignment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assignment_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignment_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignment_policy_id'), ['policy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignment_tag_id'), ['tag_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assignment_tag_id'))
        batch_op.drop_index(batch_op.f('ix_assignment_policy_id'))
        batch_op.drop_index(batch_op.f('ix_assignment_group_id'))
        batch_op.drop_index(batch_op.f('ix_assignment_device_id'))

    op.drop_table('assignment')
    with op.batch_alter_table('policy_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_policy_version_policy_id'))

    op.drop_table('policy_version')
    op.drop_table('effective_policy_cache')
    op.drop_table('device_tag_member')
    op.drop_table('device_group_member')
    op.drop_table('tag')
    with op.batch_alter_table('policy', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_policy_policy_type'))

    op.drop_table('policy')
    op.drop_table('device_group')
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_serial_number'))

    op.drop_table('device')
    # ### end Alembic commands ###
