# Copyright 2026 TAK-Solutions LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""artifacts and app packages

Revision ID: 746dc87d9b3d
Revises: e05ed1d026b2
Create Date: 2026-08-31 08:25:38.523640

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text  # autogenerate emits a bare Text() inside JSONB variants

import app.db.base  # autogenerate emits app.db.base.UtcDateTime for timestamps


revision: str = '746dc87d9b3d'
down_revision: str | None = 'e05ed1d026b2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_package',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('package_name', sa.String(length=255), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('signature_sha256', sa.String(length=64), nullable=True),
    sa.Column('signature_scheme', sa.String(length=8), nullable=True),
    sa.Column('created_at', app.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('app_package', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_package_package_name'), ['package_name'], unique=True)

    op.create_table('artifact',
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.String(length=128), nullable=False),
    sa.Column('created_at', app.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('sha256')
    )
    op.create_table('app_package_version',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('package_id', sa.Uuid(), nullable=False),
    sa.Column('version_code', sa.Integer(), nullable=False),
    sa.Column('version_name', sa.String(length=128), nullable=True),
    sa.Column('min_sdk', sa.Integer(), nullable=True),
    sa.Column('target_sdk', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', app.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['app_package.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('package_id', 'version_code', name='uq_package_version_code')
    )
    with op.batch_alter_table('app_package_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_package_version_package_id'), ['package_id'], unique=False)

    op.create_table('app_package_file',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('BASE', 'SPLIT', 'OBB', name='partrole', native_enum=False, length=8), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('split_name', sa.String(length=128), nullable=True),
    sa.Column('artifact_sha256', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['artifact_sha256'], ['artifact.sha256'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['version_id'], ['app_package_version.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('app_package_file', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_package_file_artifact_sha256'), ['artifact_sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_app_package_file_version_id'), ['version_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_package_file', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_package_file_version_id'))
        batch_op.drop_index(batch_op.f('ix_app_package_file_artifact_sha256'))

    op.drop_table('app_package_file')
    with op.batch_alter_table('app_package_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_package_version_package_id'))

    op.drop_table('app_package_version')
    op.drop_table('artifact')
    with op.batch_alter_table('app_package', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_package_package_name'))

    op.drop_table('app_package')
    # ### end Alembic commands ###
