# Copyright 2026 TAK-Solutions LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""admin attribution

Revision ID: 98f4a9ebc60f
Revises: 2a84424ae9f5
Create Date: 2026-08-31 15:56:34.074981

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text  # autogenerate emits a bare Text() inside JSONB variants

import app.db.base  # autogenerate emits app.db.base.UtcDateTime for timestamps


revision: str = '98f4a9ebc60f'
down_revision: str | None = '2a84424ae9f5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollment_token', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.String(length=128), nullable=True))

    with op.batch_alter_table('policy_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('published_by', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('policy_version', schema=None) as batch_op:
        batch_op.drop_column('published_by')

    with op.batch_alter_table('enrollment_token', schema=None) as batch_op:
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###
