# Copyright 2026 TAK-Solutions LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""device log bundles

Revision ID: b41c7e2d9a03
Revises: 8f60c7fde3f6
Create Date: 2026-08-31 22:10:00.000000

Written by hand rather than autogenerated. Every column here is NOT NULL on a new
table, so the server_default trap (D35) does not bite — but the `truncated` boolean
still carries one explicitly, because a row inserted by an older application build
mid-deploy would otherwise fail the constraint.
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text  # autogenerate emits a bare Text() inside JSONB variants

import app.db.base  # autogenerate emits app.db.base.UtcDateTime for timestamps


revision: str = 'b41c7e2d9a03'
down_revision: str | None = '8f60c7fde3f6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        'device_log_bundle',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('device_id', sa.Uuid(), nullable=False),
        sa.Column('command_id', sa.Uuid(), nullable=True),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('size_bytes', sa.Integer(), nullable=False),
        sa.Column('agent_version', sa.String(length=32), nullable=True),
        sa.Column(
            'truncated', sa.Boolean(), server_default=sa.false(), nullable=False
        ),
        sa.Column('collected_at', app.db.base.UtcDateTime(), nullable=False),
        sa.ForeignKeyConstraint(['device_id'], ['device.id'], ondelete='CASCADE'),
        # SET NULL, not CASCADE: a log bundle outlives the request that asked for
        # it. Deleting the command must not destroy the evidence it produced.
        sa.ForeignKeyConstraint(
            ['command_id'], ['device_command.id'], ondelete='SET NULL'
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_device_log_bundle_device_id'),
        'device_log_bundle',
        ['device_id'],
        unique=False,
    )


def downgrade() -> None:
    op.drop_index(
        op.f('ix_device_log_bundle_device_id'), table_name='device_log_bundle'
    )
    op.drop_table('device_log_bundle')
