# Copyright 2026 TAK-Solutions LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""device commands and convergence tracking

Revision ID: e05ed1d026b2
Revises: 29d37a3a091c
Create Date: 2026-08-31 07:52:25.542428

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

import app.db.base

revision: str = 'e05ed1d026b2'
down_revision: str | None = '29d37a3a091c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_command',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('command_type', sa.Enum('REBOOT', 'LOCK', 'WIPE', 'LOCATE', 'SCREENSHOT', 'CLEAR_APP_DATA', name='commandtype', native_enum=False, length=24), nullable=False),
    sa.Column('params', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'DISPATCHED', 'SUCCEEDED', 'FAILED', 'EXPIRED', name='commandstatus', native_enum=False, length=16), nullable=False),
    sa.Column('created_at', app.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('expires_at', app.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('dispatched_at', app.db.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('completed_at', app.db.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('result', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device_command', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_command_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_command_status'), ['status'], unique=False)

    with op.batch_alter_table('device', schema=None) as batch_op:
        # server_default is required: adding a NOT NULL column to a table that
        # already has device rows fails on Postgres without one. Autogenerate does
        # not infer it from the Python-side default.
        batch_op.add_column(
            sa.Column(
                'acked_state_version', sa.Integer(), nullable=False, server_default='0'
            )
        )
        batch_op.add_column(
            sa.Column(
                'compliance_status',
                sa.Enum(
                    'UNKNOWN',
                    'COMPLIANT',
                    'DEGRADED',
                    'FAILED',
                    name='compliancestatus',
                    native_enum=False,
                    length=16,
                ),
                nullable=False,
                server_default='UNKNOWN',
            )
        )
        batch_op.add_column(sa.Column('compliance_detail', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.drop_column('compliance_detail')
        batch_op.drop_column('compliance_status')
        batch_op.drop_column('acked_state_version')

    with op.batch_alter_table('device_command', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_command_status'))
        batch_op.drop_index(batch_op.f('ix_device_command_device_id'))

    op.drop_table('device_command')
    # ### end Alembic commands ###
