# Copyright 2026 TAK-Solutions LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""managed_file.is_data_package

⚠️ Hand-written, not autogenerated. Autogenerate never infers `server_default`,
and a NOT NULL column added without one fails on Postgres against a table that
already has rows — which `managed_file` does on every real deployment.

Every existing row is false: nothing uploaded before this migration was validated
as a data package, and claiming otherwise would offer unchecked zips to the
policy picker.

Revision ID: v2x4z6b8d0f2
Revises: t0v2x4z6b8d0
"""

from alembic import op
import sqlalchemy as sa

revision = "v2x4z6b8d0f2"
down_revision = "t0v2x4z6b8d0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column(
        "managed_file",
        sa.Column(
            "is_data_package",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )


def downgrade() -> None:
    op.drop_column("managed_file", "is_data_package")
