package org.takmdm.agent.core

import org.json.JSONObject
import org.junit.Assert.assertEquals
import org.junit.Test

/**
 * Pins the agent's canonical JSON against output generated by the server's
 * `app/security/bundle.py`.
 *
 * These expectations were produced by running the Python implementation, not this
 * one. That is the point: the two encoders are independent, and a divergence would
 * otherwise surface only as bundle signatures failing on real devices, with nothing
 * to indicate why.
 */
class CanonicalJsonTest {

    private fun encode(json: String): String =
        String(CanonicalJson.encode(JSONObject(json)), Charsets.UTF_8)

    @Test
    fun `keys are sorted`() {
        assertEquals("""{"a":2,"b":1}""", encode("""{"b":1,"a":2}"""))
    }

    @Test
    fun `nested structures sort at every level`() {
        assertEquals(
            """{"a":"x","z":{"y":[1,2,3]}}""",
            encode("""{"z":{"y":[1,2,3]},"a":"x"}""")
        )
    }

    @Test
    fun `a realistic desired-state bundle matches the server`() {
        val input = """
            {"schema_version":1,"device_id":"abc-123","state_version":7,
             "policy":{"PASSWORD":{"min_length":8},
                       "APP_CATALOG":{"blocked_packages":["com.a","com.b"]}},
             "apps":[],"files":{"required":[],"available":[]}}
        """.trimIndent()

        assertEquals(
            """{"apps":[],"device_id":"abc-123","files":{"available":[],"required":[]},""" +
                """"policy":{"APP_CATALOG":{"blocked_packages":["com.a","com.b"]},""" +
                """"PASSWORD":{"min_length":8}},"schema_version":1,"state_version":7}""",
            encode(input)
        )
    }

    @Test
    fun `non-ascii stays literal utf8`() {
        // ensure_ascii=False on the server, so an em dash and an accent are not
        // escaped. Escaping them here would break every signature on a bundle
        // containing a non-English filename.
        val text = "Regional Map Pack — café"
        assertEquals(
            "{\"name\":\"$text\"}",
            String(CanonicalJson.encode(JSONObject().put("name", text)), Charsets.UTF_8)
        )
    }

    @Test
    fun `control characters escape the way python does`() {
        // Escapes rather than literal control bytes: a raw form feed in source is
        // invisible and does not survive editing reliably.
        val value = "line1\nline2\ttab\"quote\\back\rCR\bBSFFctrl"
        val expected =
            "{\"s\":\"line1\\nline2\\ttab\\\"quote\\\\back\\rCR\\bBS\\fFF\\u0001ctrl\"}"

        assertEquals(
            expected,
            String(CanonicalJson.encode(JSONObject().put("s", value)), Charsets.UTF_8)
        )
    }

    @Test
    fun `booleans and null`() {
        assertEquals(
            """{"f":false,"n":null,"t":true}""",
            encode("""{"t":true,"f":false,"n":null}""")
        )
    }

    @Test
    fun `integers never gain a fractional part`() {
        // org.json will happily parse an integral literal into a Double; emitting
        // "8.0" where the server wrote "8" breaks the signature.
        assertEquals(
            """{"big":52400,"i":8,"neg":-3}""",
            encode("""{"i":8,"neg":-3,"big":52400}""")
        )
    }

    @Test
    fun `whole doubles collapse to integers`() {
        assertEquals(
            """{"v":8}""",
            String(CanonicalJson.encode(JSONObject().put("v", 8.0)), Charsets.UTF_8)
        )
    }

    @Test
    fun `empty containers`() {
        assertEquals("""{"a":[],"o":{}}""", encode("""{"o":{},"a":[]}"""))
    }
}
